[tool.poetry]
name = "gbatchexecute"
version = "0.1.0"
description = "Library to ease interactions with Google's batchexecute batch RPC system"
authors = ["Pierre Nicolas Durette <pndurette@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pydoc-markdown = "^3.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
