name: Generate Docs

on:
  pull_request:
    paths:
      - '**.py'
      - '!**/test_*.py'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install docs dependencies
      run: |
        pip install --upgrade pip
        pip install '.[docs]' 
    - name: Generate docs
      run: pydoc-markdown
    - name: Push docs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate docs
        file_pattern: docs/*