name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: pybatchexecute
      
      # Only do the rest (package build/push) if a release was created
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
      - name: Setup Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install build dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: python -m build
      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@a56da0b891b3dc519c7ee3284aff1fad93cc8598
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

# References:
# * Release Please:
#   https://github.com/googleapis/release-please
# * Release Please (GitHub Action)
#   https://github.com/google-github-actions/release-please-action
# * Conventional Commits:
#   https://www.conventionalcommits.org/